[package]
name = "table2img"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "table2img"
path = "src/main.rs"

[dependencies]
image = "0.25"
imageproc = "0.25"
ab_glyph = "0.2"
clap = { version = "4", features = ["derive"] }
